INSERT INTO vehicles (id, vehicle, brand, year, description, sold, color, created_at, updated_at)
VALUES (gen_random_uuid(), 'Civic', 'Honda', 2001, 'Sedã compacto confiável', false, 'Prata', NOW(), NOW()),
       (gen_random_uuid(), 'Corolla', 'Toyota', 2002, 'Sedã médio econômico', true, 'Preto', NOW(), NOW()),
       (gen_random_uuid(), 'Golf', 'Volkswagen', 2003, 'Hatchback esportivo', false, 'Vermelho', NOW(), NOW()),
       (gen_random_uuid(), 'Focus', 'Ford', 2004, 'Hatchback popular', true, 'Azul', NOW(), NOW()),
       (gen_random_uuid(), 'Palio', 'Fiat', 2005, 'Hatchback urbano', false, 'Branco', NOW(), NOW()),
       (gen_random_uuid(), 'Gol', 'Volkswagen', 2006, 'Hatchback nacional', true, 'Prata', NOW(), NOW()),
       (gen_random_uuid(), 'Fiesta', 'Ford', 2007, 'Hatchback compacto', false, 'Verde', NOW(), NOW()),
       (gen_random_uuid(), 'Celta', 'Chevrolet', 2008, 'Hatchback entry-level', true, 'Cinza', NOW(), NOW()),
       (gen_random_uuid(), 'Uno', 'Fiat', 2009, 'Hatchback clássico', false, 'Vermelho', NOW(), NOW()),
       (gen_random_uuid(), 'Ka', 'Ford', 2000, 'Hatchback urbano compacto', true, 'Amarelo', NOW(), NOW()),
       (gen_random_uuid(), 'Astra', 'Chevrolet', 2001, 'Sedã médio', false, 'Preto', NOW(), NOW()),
       (gen_random_uuid(), 'Tucson', 'Hyundai', 2007, 'SUV médio', false, 'Prata', NOW(), NOW()),
       (gen_random_uuid(), 'CR-V', 'Honda', 2008, 'SUV compacto', true, 'Branco', NOW(), NOW()),
       (gen_random_uuid(), 'Hilux', 'Toyota', 2009, 'Picape robusta', false, 'Preto', NOW(), NOW()),
       (gen_random_uuid(), 'Ranger', 'Ford', 2005, 'Picape versátil', true, 'Azul', NOW(), NOW()),
       (gen_random_uuid(), 'Montana', 'Chevrolet', 2004, 'Picape compacta', false, 'Branco', NOW(), NOW()),
       (gen_random_uuid(), 'Strada', 'Fiat', 2006, 'Picape leve', true, 'Vermelho', NOW(), NOW());

INSERT INTO vehicles (id, vehicle, brand, year, description, sold, color, created_at, updated_at)
VALUES (gen_random_uuid(), 'HB20', 'Hyundai', 2013, 'Hatchback moderno', false, 'Branco', NOW(), NOW()),
       (gen_random_uuid(), 'Onix', 'Chevrolet', 2014, 'Hatchback líder de vendas', true, 'Prata', NOW(), NOW()),
       (gen_random_uuid(), 'Argo', 'Fiat', 2018, 'Hatchback premium', false, 'Vermelho', NOW(), NOW()),
       (gen_random_uuid(), 'Kicks', 'Nissan', 2017, 'SUV compacto urbano', true, 'Laranja', NOW(), NOW()),
       (gen_random_uuid(), 'Compass', 'Jeep', 2018, 'SUV médio aventureiro', false, 'Preto', NOW(), NOW()),
       (gen_random_uuid(), 'Renegade', 'Jeep', 2016, 'SUV compacto robusto', true, 'Verde', NOW(), NOW()),
       (gen_random_uuid(), 'T-Cross', 'Volkswagen', 2019, 'SUV compacto tecnológico', false, 'Cinza', NOW(), NOW()),
       (gen_random_uuid(), 'Creta', 'Hyundai', 2017, 'SUV compacto espaçoso', true, 'Branco', NOW(), NOW()),
       (gen_random_uuid(), 'Duster', 'Renault', 2015, 'SUV aventureiro', false, 'Prata', NOW(), NOW()),
       (gen_random_uuid(), 'EcoSport', 'Ford', 2013, 'SUV compacto popular', true, 'Azul', NOW(), NOW()),
       (gen_random_uuid(), 'Civic', 'Honda', 2019, 'Sedã premium', false, 'Preto', NOW(), NOW()),
       (gen_random_uuid(), 'Cruze', 'Chevrolet', 2018, 'Sedã médio confortável', true, 'Branco', NOW(), NOW()),
       (gen_random_uuid(), 'Jetta', 'Volkswagen', 2016, 'Sedã executivo', false, 'Cinza', NOW(), NOW()),
       (gen_random_uuid(), 'Corolla', 'Toyota', 2019, 'Sedã híbrido', true, 'Prata', NOW(), NOW()),
       (gen_random_uuid(), 'City', 'Honda', 2015, 'Sedã compacto', false, 'Vermelho', NOW(), NOW()),
       (gen_random_uuid(), 'Sandero', 'Renault', 2014, 'Hatchback versátil', true, 'Branco', NOW(), NOW()),
       (gen_random_uuid(), 'Etios', 'Toyota', 2017, 'Hatchback confiável', false, 'Prata', NOW(), NOW());

INSERT INTO vehicles (id, vehicle, brand, year, description, sold, color, created_at, updated_at)
VALUES (gen_random_uuid(), 'Nivus', 'Volkswagen', 2021, 'SUV cupê compacto', false, 'Azul', NOW(), NOW()),
       (gen_random_uuid(), 'Taos', 'Volkswagen', 2022, 'SUV médio premium', true, 'Cinza', NOW(), NOW()),
       (gen_random_uuid(), 'Fastback', 'Fiat', 2023, 'SUV cupê esportivo', false, 'Vermelho', NOW(), NOW()),
       (gen_random_uuid(), 'Pulse', 'Fiat', 2022, 'SUV compacto moderno', true, 'Branco', NOW(), NOW()),
       (gen_random_uuid(), 'Tracker', 'Chevrolet', 2021, 'SUV compacto tecnológico', false, 'Preto', NOW(), NOW()),
       (gen_random_uuid(), 'S10', 'Chevrolet', 2024, 'Picape robusta', true, 'Branco', NOW(), NOW()),
       (gen_random_uuid(), 'Toro', 'Fiat', 2023, 'Picape média versátil', false, 'Prata', NOW(), NOW()),
       (gen_random_uuid(), 'Maverick', 'Ford', 2024, 'Picape compacta híbrida', true, 'Azul', NOW(), NOW()),
       (gen_random_uuid(), 'Corolla Cross', 'Toyota', 2022, 'SUV médio híbrido', false, 'Preto', NOW(), NOW()),
       (gen_random_uuid(), 'RAV4', 'Toyota', 2023, 'SUV médio premium', true, 'Prata', NOW(), NOW()),
       (gen_random_uuid(), 'HR-V', 'Honda', 2023, 'SUV compacto premium', false, 'Branco', NOW(), NOW()),
       (gen_random_uuid(), 'Seltos', 'Kia', 2021, 'SUV compacto conectado', true, 'Cinza', NOW(), NOW()),
       (gen_random_uuid(), 'Sportage', 'Kia', 2024, 'SUV médio sofisticado', false, 'Verde', NOW(), NOW()),
       (gen_random_uuid(), 'Tucson', 'Hyundai', 2023, 'SUV médio tecnológico', true, 'Preto', NOW(), NOW()),
       (gen_random_uuid(), 'Commander', 'Jeep', 2023, 'SUV grande sete lugares', false, 'Cinza', NOW(), NOW()),
       (gen_random_uuid(), 'Cronos', 'Fiat', 2020, 'Sedã médio confortável', true, 'Branco', NOW(), NOW());